
name: decode_signals_of_creatures_and_plants
description: Flutter app 'Creatures Decoder' — record, playback, spectrogram, and ML scaffold.
publish_to: "none"
version: 0.2.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  ffmpeg_kit_flutter_min_gpl: ^6.0.3
  tflite_flutter: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/labels.txt
